version: '3.9'

services:
  etl-mysql-in-service:
    image: mysql:latest
    container_name: etl-mysql-in-service
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - '3306:3306'
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - etl-backend
  etl-mysql-out-service:
    image: mysql:latest
    container_name: etl-mysql-out-service
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - '3307:3306'
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - etl-backend
  etl-redis-service:
    image: redis:latest
    container_name: etl-redis-service
    ports:
      - '6379:6379'
    networks:
      - etl-backend
networks:
  etl-backend:
    driver: bridge