#spring setting
spring:
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password:
      database: 0
# multiple datasource configuration
app:
  datasource:
    input:
      url: jdbc:mysql://localhost:3306/your_db_name
      username: your_db_username
      password: your_db_password
    output:
      url: jdbc:mysql://localhost:3306/your_db_name
      username: your_db_username
      password: your_db_password