#server setting
server:
  port: 8080
#spring setting
spring:
  application:
    name: etl
  profiles:
    active: dev
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 0
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        jdbc:
          time_zone: UTC-7
        dialect: org.hibernate.dialect.MySQL8Dialect
  jackson:
    serialization:
      indent-output: true
# multiple datasource configuration
app:
  datasource:
    input:
      url: jdbc:mysql://localhost:3306/database_read
      username: root
      password: 123456
    output:
      url: jdbc:mysql://localhost:3307/database_write
      username: root
      password: 123456